name: prody
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anyio=4.2.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - idna=3.7
  - ipykernel=6.28.0
  - ipython=8.25.0
  - jedi=0.18.1
  - jinja2=3.1.4
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy-base=1.26.4
  - openjpeg=2.3.0
  - openssl=3.0.14
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - biopython==1.79
      - numpy==1.23.5
      - prody==2.4.1
      - pyparsing==3.1.2
      - scipy==1.13.1
